### ISSUE TITLE
Proposal for a better templated YahooFinanceD

### ISSUE THREAD

**Issue by m3m0ry** [SelimOzel/YahooFinanceD#1]
(I'm the one from the forum :) )

You could give the template for writing/mining/logging during the type creation, not during the function call. (Because why would you want to log first in json, and then in something else?)

The [checkedint](https://dlang.org/phobos/std_experimental_checkedint.html) does something similar.
I am no D expert myself, i learned this method 2 days ago. I thought I just share this possibility with you, since I liked it a lot.

I would create your struct with:
```
auto miner = YahooFinanceD!(JsonWriter, NoLogger);
```
where `JsonWriter` would be a struct, which provides the write function.
The write function in `YahooFinanceD` would just call it's template write function.
NoLogger could have just an empty log function

**Comment by SelimOzel** [comment]
I agree the template looks weird at this point and I might update it in the coming weeks - but don't rely on it :) . The thing is Yahoo sends the data as json by default. So as I was writing the code for the first time, it was just easy/fast to write as json. 

Having said that, you don't have to write json first. You can write the following. AAPL's price/div/split data will be written inside the apple frame. It won't log anything.
`string name = "AAPL";`
`Date begin = Date(1980, 12, 12);`
`Date end = Date(2020, 6, 10);`
`YahooFinanceD simpleMiner;`
`simpleMiner.Mine!(logger.off)(begin, end, name); // by default, grabs daily data`
`Frame[] apple = simpleMiner.Write!(output.frame, logger.off, Frame[]);`

Let me know if that's what you had in mind. If it is, I can put an example code in the repository.

S

**Comment by m3m0ry** [comment]
Not entirely what I had in mind, but it works as well. Thanks.
